17:25:03.167 [error] |undefined|kzs_plan:574(<0.1372.0>) error reloading dataplans {error,not_found}
17:25:03.620 [error] |00000000000|kz_util:97(<0.1286.0>) stacktrace: 
17:25:03.620 [error] |00000000000|kz_util:104(<0.1286.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:25:03.620 [error] |00000000000|kz_util:104(<0.1286.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (229)
17:25:03.620 [error] |00000000000|kz_util:104(<0.1286.0>) st: kz_datamgr:init_dbs/1 at (1674)
17:25:03.620 [error] |00000000000|kz_util:104(<0.1286.0>) st: kazoo_data_bootstrap:start_link/0 at (25)
17:25:03.620 [error] |00000000000|kz_util:104(<0.1286.0>) st: supervisor:do_start_child/2 at (365)
17:25:03.620 [error] |00000000000|kz_util:104(<0.1286.0>) st: supervisor:start_children/3 at (348)
17:25:03.621 [error] |00000000000|kz_util:104(<0.1286.0>) st: supervisor:init_children/2 at (314)
17:25:03.621 [error] |00000000000|kz_util:104(<0.1286.0>) st: gen_server:init_it/6 at (328)
17:25:03.928 [critical] |0000000000|kz_couch_util:69(<0.1381.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:25:04.072 [critical] |0000000000|kz_couch_util:69(<0.1381.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:25:04.211 [error] |0000000000|kz_datamgr:1328(<0.1381.0>) error getting registered view : not_found
17:25:05.819 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:25:05.866 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:25:05.895 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:25:05.929 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:25:05.951 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:25:05.979 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:25:06.002 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:25:06.273 [critical] |00000000000|kz_couch_util:69(<0.1428.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"read_failure\"}\n">>
17:25:06.285 [critical] |00000000000|kz_couch_util:69(<0.1428.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"read_failure\"}\n">>
17:25:06.405 [critical] |00000000000|kz_couch_util:69(<0.1428.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"read_failure\"}\n">>
17:25:06.743 [error] |0000000000|kz_datamgr:1328(<0.1701.0>) error getting registered view : not_found
17:25:06.755 [critical] |0000000000|kz_couch_util:69(<0.1701.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:25:06.756 [error] |0000000000|kz_util:97(<0.1701.0>) stacktrace: 
17:25:06.760 [error] |0000000000|kz_util:104(<0.1701.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:25:06.760 [error] |0000000000|kz_util:104(<0.1701.0>) st: kazoo_auth_app:start/2 at (22)
17:25:06.760 [error] |0000000000|kz_util:104(<0.1701.0>) st: application_master:start_it_old/4 at (273)
17:25:06.779 [critical] |0000000000|kz_couch_util:69(<0.1701.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:25:06.780 [error] |0000000000|kz_util:97(<0.1701.0>) stacktrace: 
17:25:06.780 [error] |0000000000|kz_util:104(<0.1701.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:25:06.780 [error] |0000000000|kz_util:104(<0.1701.0>) st: kazoo_auth_app:start/2 at (22)
17:25:06.780 [error] |0000000000|kz_util:104(<0.1701.0>) st: application_master:start_it_old/4 at (273)
17:25:06.803 [critical] |0000000000|kz_couch_util:69(<0.1701.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:25:06.803 [error] |0000000000|kz_util:97(<0.1701.0>) stacktrace: 
17:25:06.803 [error] |0000000000|kz_util:104(<0.1701.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:25:06.803 [error] |0000000000|kz_util:104(<0.1701.0>) st: kazoo_auth_app:start/2 at (22)
17:25:06.803 [error] |0000000000|kz_util:104(<0.1701.0>) st: application_master:start_it_old/4 at (273)
17:25:06.822 [critical] |0000000000|kz_couch_util:69(<0.1701.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:25:06.822 [error] |0000000000|kz_util:97(<0.1701.0>) stacktrace: 
17:25:06.822 [error] |0000000000|kz_util:104(<0.1701.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:25:06.822 [error] |0000000000|kz_util:104(<0.1701.0>) st: kazoo_auth_app:start/2 at (22)
17:25:06.822 [error] |0000000000|kz_util:104(<0.1701.0>) st: application_master:start_it_old/4 at (273)
17:25:06.849 [critical] |0000000000|kz_couch_util:69(<0.1701.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:25:06.849 [error] |0000000000|kz_util:97(<0.1701.0>) stacktrace: 
17:25:06.849 [error] |0000000000|kz_util:104(<0.1701.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:25:06.849 [error] |0000000000|kz_util:104(<0.1701.0>) st: kazoo_auth_app:start/2 at (22)
17:25:06.849 [error] |0000000000|kz_util:104(<0.1701.0>) st: application_master:start_it_old/4 at (273)
17:25:06.869 [critical] |0000000000|kz_couch_util:69(<0.1701.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"read_failure\"}\n">>
17:25:06.942 [critical] |0000000000|kz_couch_util:69(<0.1731.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:25:07.248 [critical] |0000000000|kz_couch_util:69(<0.1731.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:25:07.253 [error] |0000000000|Undefined:Undefined(<0.1731.0>) Supervisor kazoo_auth_sup had child kz_auth_init started with kz_auth_init:start_link() at undefined exit with reason {'EXIT',{{badmatch,{error,<<"internal_server_error">>}},[{kz_auth_keys,public_key,1,[{file,"src/kz_auth_keys.erl"},{line,245}]},{kz_auth_init,start_link,0,[{file,"src/kz_auth_init.erl"},{line,18}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"p..."},...]}]}} in context start_error
17:25:07.269 [error] |0000000000|Undefined:Undefined(<0.1700.0>) CRASH REPORT Process <0.1700.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,kz_auth_init,{'EXIT',{{badmatch,{error,<<"internal_server_error">>}},[{kz_auth_keys,public_key,1,[{file,"src/kz_auth_keys.erl"},{line,245}]},{kz_auth_init,start_link,0,[{file,"src/kz_auth_init.erl"},{line,18}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,...}]},...]}}}},...} in application_master:init/4 line 134
17:25:07.280 [error] |00000000000|kapps_controller:107(<0.1428.0>) ecallmgr could not start: {kazoo_auth,{{shutdown,{failed_to_start_child,kz_auth_init,{'EXIT',{{badmatch,{error,<<"internal_server_error">>}},[{kz_auth_keys,public_key,1,[{file,"src/kz_auth_keys.erl"},{line,245}]},{kz_auth_init,start_link,0,[{file,"src/kz_auth_init.erl"},{line,18}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{kazoo_auth_app,start,[normal,[]]}}}
17:29:03.438 [error] |undefined|kzs_plan:574(<0.1372.0>) error reloading dataplans {error,not_found}
17:29:03.550 [error] |00000000000|kz_util:97(<0.1286.0>) stacktrace: 
17:29:03.550 [error] |00000000000|kz_util:104(<0.1286.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:29:03.550 [error] |00000000000|kz_util:104(<0.1286.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (229)
17:29:03.550 [error] |00000000000|kz_util:104(<0.1286.0>) st: kz_datamgr:init_dbs/1 at (1674)
17:29:03.550 [error] |00000000000|kz_util:104(<0.1286.0>) st: kazoo_data_bootstrap:start_link/0 at (25)
17:29:03.550 [error] |00000000000|kz_util:104(<0.1286.0>) st: supervisor:do_start_child/2 at (365)
17:29:03.550 [error] |00000000000|kz_util:104(<0.1286.0>) st: supervisor:start_children/3 at (348)
17:29:03.550 [error] |00000000000|kz_util:104(<0.1286.0>) st: supervisor:init_children/2 at (314)
17:29:03.550 [error] |00000000000|kz_util:104(<0.1286.0>) st: gen_server:init_it/6 at (328)
17:29:03.823 [critical] |0000000000|kz_couch_util:69(<0.1380.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:29:04.024 [critical] |0000000000|kz_couch_util:69(<0.1380.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:29:04.133 [error] |0000000000|kz_datamgr:1328(<0.1380.0>) error getting registered view : not_found
17:29:04.280 [critical] |0000000000|kz_couch_util:69(<0.1456.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:29:05.638 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:29:05.695 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:29:05.720 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:29:05.751 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:29:05.781 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:29:05.836 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:29:05.861 [error] |00000000000|kz_datamgr:1328(<0.1428.0>) error getting registered view : not_found
17:29:06.063 [critical] |00000000000|kz_couch_util:69(<0.1428.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"read_failure\"}\n">>
17:29:06.074 [critical] |00000000000|kz_couch_util:69(<0.1428.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"read_failure\"}\n">>
17:29:06.166 [critical] |00000000000|kz_couch_util:69(<0.1428.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"read_failure\"}\n">>
17:29:06.527 [error] |0000000000|kz_datamgr:1328(<0.1717.0>) error getting registered view : not_found
17:29:06.550 [critical] |0000000000|kz_couch_util:69(<0.1717.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:29:06.550 [error] |0000000000|kz_util:97(<0.1717.0>) stacktrace: 
17:29:06.551 [error] |0000000000|kz_util:104(<0.1717.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:29:06.551 [error] |0000000000|kz_util:104(<0.1717.0>) st: kazoo_auth_app:start/2 at (22)
17:29:06.551 [error] |0000000000|kz_util:104(<0.1717.0>) st: application_master:start_it_old/4 at (273)
17:29:06.581 [critical] |0000000000|kz_couch_util:69(<0.1717.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:29:06.581 [error] |0000000000|kz_util:97(<0.1717.0>) stacktrace: 
17:29:06.581 [error] |0000000000|kz_util:104(<0.1717.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:29:06.582 [error] |0000000000|kz_util:104(<0.1717.0>) st: kazoo_auth_app:start/2 at (22)
17:29:06.582 [error] |0000000000|kz_util:104(<0.1717.0>) st: application_master:start_it_old/4 at (273)
17:29:06.622 [critical] |0000000000|kz_couch_util:69(<0.1717.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:29:06.623 [error] |0000000000|kz_util:97(<0.1717.0>) stacktrace: 
17:29:06.623 [error] |0000000000|kz_util:104(<0.1717.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:29:06.623 [error] |0000000000|kz_util:104(<0.1717.0>) st: kazoo_auth_app:start/2 at (22)
17:29:06.623 [error] |0000000000|kz_util:104(<0.1717.0>) st: application_master:start_it_old/4 at (273)
17:29:06.643 [critical] |0000000000|kz_couch_util:69(<0.1717.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:29:06.646 [error] |0000000000|kz_util:97(<0.1717.0>) stacktrace: 
17:29:06.646 [error] |0000000000|kz_util:104(<0.1717.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:29:06.647 [error] |0000000000|kz_util:104(<0.1717.0>) st: kazoo_auth_app:start/2 at (22)
17:29:06.647 [error] |0000000000|kz_util:104(<0.1717.0>) st: application_master:start_it_old/4 at (273)
17:29:06.669 [critical] |0000000000|kz_couch_util:69(<0.1717.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:29:06.669 [error] |0000000000|kz_util:97(<0.1717.0>) stacktrace: 
17:29:06.669 [error] |0000000000|kz_util:104(<0.1717.0>) st: kz_datamgr:do_revise_docs_from_folder/3 at (226)
17:29:06.669 [error] |0000000000|kz_util:104(<0.1717.0>) st: kazoo_auth_app:start/2 at (22)
17:29:06.669 [error] |0000000000|kz_util:104(<0.1717.0>) st: application_master:start_it_old/4 at (273)
17:29:06.682 [critical] |0000000000|kz_couch_util:69(<0.1717.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"read_failure\"}\n">>
17:29:06.751 [critical] |0000000000|kz_couch_util:69(<0.1746.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:29:07.065 [critical] |0000000000|kz_couch_util:69(<0.1746.0>) response code 500 not expected : <<"{\"error\":\"error\",\"reason\":\"internal_server_error\"}\n">>
17:29:07.069 [error] |0000000000|Undefined:Undefined(<0.1746.0>) Supervisor kazoo_auth_sup had child kz_auth_init started with kz_auth_init:start_link() at undefined exit with reason {'EXIT',{{badmatch,{error,<<"internal_server_error">>}},[{kz_auth_keys,public_key,1,[{file,"src/kz_auth_keys.erl"},{line,245}]},{kz_auth_init,start_link,0,[{file,"src/kz_auth_init.erl"},{line,18}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"p..."},...]}]}} in context start_error
17:29:07.084 [error] |0000000000|Undefined:Undefined(<0.1716.0>) CRASH REPORT Process <0.1716.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,kz_auth_init,{'EXIT',{{badmatch,{error,<<"internal_server_error">>}},[{kz_auth_keys,public_key,1,[{file,"src/kz_auth_keys.erl"},{line,245}]},{kz_auth_init,start_link,0,[{file,"src/kz_auth_init.erl"},{line,18}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,...}]},...]}}}},...} in application_master:init/4 line 134
17:29:07.094 [error] |00000000000|kapps_controller:107(<0.1428.0>) ecallmgr could not start: {kazoo_auth,{{shutdown,{failed_to_start_child,kz_auth_init,{'EXIT',{{badmatch,{error,<<"internal_server_error">>}},[{kz_auth_keys,public_key,1,[{file,"src/kz_auth_keys.erl"},{line,245}]},{kz_auth_init,start_link,0,[{file,"src/kz_auth_init.erl"},{line,18}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{kazoo_auth_app,start,[normal,[]]}}}
18:56:29.755 [error] |0000000000|Undefined:Undefined(<0.1360.0>) ** Connection attempt from disallowed node 'sup_a806@kazoo1-z100.hpbx.lxd' ** 
18:57:06.396 [error] |undefined|kzs_plan:574(<0.1374.0>) error reloading dataplans {error,not_found}
19:00:13.680 [error] |0000000000|Undefined:Undefined(<0.213.0>) gen_server <0.213.0> terminated with reason: socket_closed_unexpectedly
19:00:13.680 [error] |0000000000|Undefined:Undefined(<0.213.0>) CRASH REPORT Process <0.213.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/7 line 812
19:00:13.712 [error] |0000000000|Undefined:Undefined(<0.213.0>) gen_server <0.213.0> terminated with reason: socket_closed_unexpectedly
19:00:13.682 [critical] |00000000000|kz_amqp_connection:196(<0.210.0>) connection to the AMQP broker amqp://guest:guest@rabbit1-z100.hpbx.lxd:5672 (<0.213.0>) died: socket_closed_unexpectedly
19:00:13.714 [error] |0000000000|Undefined:Undefined(<0.213.0>) CRASH REPORT Process <0.213.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/7 line 812
19:00:13.716 [critical] |00000000000|kz_amqp_connection:196(<0.210.0>) connection to the AMQP broker amqp://guest:guest@rabbit1-z100.hpbx.lxd:5672 (<0.213.0>) died: socket_closed_unexpectedly
19:00:13.683 [critical] |00000000000|kz_amqp_connection:196(<0.209.0>) connection to the AMQP broker amqp://guest:guest@rabbit1-z200.hpbx.lxd:5672 (<0.216.0>) died: socket_closed_unexpectedly
19:00:13.717 [critical] |00000000000|kz_amqp_connection:196(<0.209.0>) connection to the AMQP broker amqp://guest:guest@rabbit1-z200.hpbx.lxd:5672 (<0.216.0>) died: socket_closed_unexpectedly
19:00:13.725 [error] |0000000000|Undefined:Undefined(<0.216.0>) gen_server <0.216.0> terminated with reason: socket_closed_unexpectedly
19:00:13.725 [error] |0000000000|Undefined:Undefined(<0.216.0>) CRASH REPORT Process <0.216.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/7 line 812
19:00:13.730 [error] |0000000000|Undefined:Undefined(<0.211.0>) Supervisor {<0.211.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.212.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"rabbit1-z100.hpbx.lxd",5672,2047,0,10,500,...}) at <0.213.0> exit with reason socket_closed_unexpectedly in context child_terminated
19:00:13.737 [error] |0000000000|Undefined:Undefined(<0.211.0>) Supervisor {<0.211.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.212.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"rabbit1-z100.hpbx.lxd",5672,2047,0,10,500,...}) at <0.213.0> exit with reason reached_max_restart_intensity in context shutdown
19:00:13.740 [error] |0000000000|Undefined:Undefined(<0.214.0>) Supervisor {<0.214.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.215.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"rabbit1-z200.hpbx.lxd",5672,2047,0,10,500,...}) at <0.216.0> exit with reason socket_closed_unexpectedly in context child_terminated
19:00:13.744 [error] |0000000000|Undefined:Undefined(<0.214.0>) Supervisor {<0.214.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.215.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"rabbit1-z200.hpbx.lxd",5672,2047,0,10,500,...}) at <0.216.0> exit with reason reached_max_restart_intensity in context shutdown
19:00:13.684 [error] |0000000000|Undefined:Undefined(<0.216.0>) gen_server <0.216.0> terminated with reason: socket_closed_unexpectedly
19:00:13.744 [error] |0000000000|Undefined:Undefined(<0.225.0>) gen_server <0.225.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
19:00:13.684 [error] |0000000000|Undefined:Undefined(<0.216.0>) CRASH REPORT Process <0.216.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/7 line 812
19:00:13.745 [error] |0000000000|Undefined:Undefined(<0.225.0>) CRASH REPORT Process <0.225.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 812
19:00:13.690 [error] |0000000000|Undefined:Undefined(<0.211.0>) Supervisor {<0.211.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.212.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"rabbit1-z100.hpbx.lxd",5672,2047,0,10,500,...}) at <0.213.0> exit with reason socket_closed_unexpectedly in context child_terminated
19:00:13.745 [error] |0000000000|Undefined:Undefined(<0.223.0>) Supervisor {<0.223.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.213.0>, 1, <0.224.0>, {<<"client 10.112.75.72:49825 -> 10.112.75.18:5672">>,1}) at <0.225.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context child_terminated
19:00:13.746 [error] |0000000000|Undefined:Undefined(<0.223.0>) Supervisor {<0.223.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.213.0>, 1, <0.224.0>, {<<"client 10.112.75.72:49825 -> 10.112.75.18:5672">>,1}) at <0.225.0> exit with reason reached_max_restart_intensity in context shutdown
19:00:13.693 [error] |0000000000|Undefined:Undefined(<0.211.0>) Supervisor {<0.211.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.212.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"rabbit1-z100.hpbx.lxd",5672,2047,0,10,500,...}) at <0.213.0> exit with reason reached_max_restart_intensity in context shutdown
19:00:13.748 [error] |0000000000|Undefined:Undefined(<0.275.0>) gen_server <0.275.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
19:00:13.748 [error] |0000000000|Undefined:Undefined(<0.275.0>) CRASH REPORT Process <0.275.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 812
19:00:13.695 [error] |0000000000|Undefined:Undefined(<0.214.0>) Supervisor {<0.214.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.215.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"rabbit1-z200.hpbx.lxd",5672,2047,0,10,500,...}) at <0.216.0> exit with reason socket_closed_unexpectedly in context child_terminated
19:00:13.755 [error] |0000000000|Undefined:Undefined(<0.273.0>) Supervisor {<0.273.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.216.0>, 1, <0.274.0>, {<<"client 10.112.75.72:40733 -> 10.112.75.11:5672">>,1}) at <0.275.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context child_terminated
19:00:13.703 [error] |0000000000|Undefined:Undefined(<0.214.0>) Supervisor {<0.214.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.215.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"rabbit1-z200.hpbx.lxd",5672,2047,0,10,500,...}) at <0.216.0> exit with reason reached_max_restart_intensity in context shutdown
19:00:13.763 [error] |0000000000|Undefined:Undefined(<0.273.0>) Supervisor {<0.273.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.216.0>, 1, <0.274.0>, {<<"client 10.112.75.72:40733 -> 10.112.75.11:5672">>,1}) at <0.275.0> exit with reason reached_max_restart_intensity in context shutdown
19:00:13.704 [error] |0000000000|Undefined:Undefined(<0.225.0>) gen_server <0.225.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
19:00:13.707 [error] |0000000000|Undefined:Undefined(<0.225.0>) CRASH REPORT Process <0.225.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 812
19:00:13.709 [error] |0000000000|Undefined:Undefined(<0.223.0>) Supervisor {<0.223.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.213.0>, 1, <0.224.0>, {<<"client 10.112.75.72:54257 -> 10.112.75.18:5672">>,1}) at <0.225.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context child_terminated
19:00:13.710 [error] |0000000000|Undefined:Undefined(<0.223.0>) Supervisor {<0.223.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.213.0>, 1, <0.224.0>, {<<"client 10.112.75.72:54257 -> 10.112.75.18:5672">>,1}) at <0.225.0> exit with reason reached_max_restart_intensity in context shutdown
19:00:13.724 [error] |0000000000|Undefined:Undefined(<0.275.0>) gen_server <0.275.0> terminated with reason: {infrastructure_died,{writer,send_failed,badarg}}
19:00:13.724 [error] |0000000000|Undefined:Undefined(<0.275.0>) CRASH REPORT Process <0.275.0> with 0 neighbours exited with reason: {infrastructure_died,{writer,send_failed,badarg}} in gen_server:terminate/7 line 812
19:00:13.730 [error] |0000000000|Undefined:Undefined(<0.273.0>) Supervisor {<0.273.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.216.0>, 1, <0.274.0>, {<<"client 10.112.75.72:33987 -> 10.112.75.11:5672">>,1}) at <0.275.0> exit with reason {infrastructure_died,{writer,send_failed,badarg}} in context child_terminated
19:00:13.736 [error] |0000000000|Undefined:Undefined(<0.273.0>) Supervisor {<0.273.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.216.0>, 1, <0.274.0>, {<<"client 10.112.75.72:33987 -> 10.112.75.11:5672">>,1}) at <0.275.0> exit with reason reached_max_restart_intensity in context shutdown
19:00:13.875 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:97(<0.1239.0>) stacktrace: 
19:00:13.876 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:106(<0.1239.0>) st: proplists:get_value at 226
19:00:13.877 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:107(<0.1239.0>) args: port
19:00:13.877 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:107(<0.1239.0>) args: {error,no_scheme}
19:00:13.878 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:107(<0.1239.0>) args: undefined
19:00:13.878 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:104(<0.1239.0>) st: amqp_uri:remove_credentials/1 at (35)
19:00:13.878 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:104(<0.1239.0>) st: kz_nodes:normalize_amqp_uri/1 at (931)
19:00:13.878 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:104(<0.1239.0>) st: kz_nodes:maybe_add_zone/2 at (1227)
19:00:13.878 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:104(<0.1239.0>) st: kz_nodes:handle_cast/2 at (771)
19:00:13.880 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:104(<0.1239.0>) st: gen_listener:handle_module_cast/2 at (1324)
19:00:13.880 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:104(<0.1239.0>) st: gen_server:try_dispatch/4 at (601)
19:00:13.880 [error] |f59f3049-3d81-48b1-872c-7d0a9d7e0f29|kz_util:104(<0.1239.0>) st: gen_server:handle_msg/5 at (667)
19:00:13.884 [error] |0000000000|Undefined:Undefined(<0.1239.0>) gen_server kz_nodes terminated with reason: function_clause
19:00:14.008 [error] |0000000000|gen_server:812(<0.1239.0>) CRASH REPORT Process kz_nodes with 0 neighbours exited with reason: no function clause matching gen_server:terminate/7 line 812
19:00:14.012 [error] |0000000000|Undefined:Undefined(<0.783.0>) Supervisor kazoo_globals_sup had child kz_nodes started with kz_nodes:start_link() at <0.1239.0> exit with reason function_clause in context child_terminated
